from django.urls import path
from . import views

urlpatterns = [
    path("partial/", views.classifiers_partial, name="classifiers_partial"),
    path("country-code/", views.country_code_lookup, name="country_code_lookup"),
    path("okv/countries-for-date/", views.okv_countries_for_date, name="okv_countries_for_date"),
    # Реестр бизнес-сущностей
    path("ber/table/", views.ber_table_partial, name="ber_table_partial"),
    path("ber/filter-options/", views.business_entity_filter_options, name="business_entity_filter_options"),
    path("ber/create/", views.ber_form_create, name="ber_form_create"),
    path("ber/<int:pk>/edit/", views.ber_form_edit, name="ber_form_edit"),
    path("ber/<int:pk>/delete/", views.ber_delete, name="ber_delete"),
    path("ber/<int:pk>/move-up/", views.ber_move_up, name="ber_move_up"),
    path("ber/<int:pk>/move-down/", views.ber_move_down, name="ber_move_down"),
    # Реестр идентификаторов
    path("bei/table/", views.bei_table_partial, name="bei_table_partial"),
    path("bei/create/", views.bei_form_create, name="bei_form_create"),
    path("bei/<int:pk>/edit/", views.bei_form_edit, name="bei_form_edit"),
    path("bei/<int:pk>/delete/", views.bei_delete, name="bei_delete"),
    path("bei/<int:pk>/move-up/", views.bei_move_up, name="bei_move_up"),
    path("bei/<int:pk>/move-down/", views.bei_move_down, name="bei_move_down"),
    # Реестр атрибутов
    path("bat/table/", views.bat_table_partial, name="bat_table_partial"),
    path("bat/create/", views.bat_form_create, name="bat_form_create"),
    path("bat/<int:pk>/edit/", views.bat_form_edit, name="bat_form_edit"),
    path("bat/<int:pk>/delete/", views.bat_delete, name="bat_delete"),
    path("bat/<int:pk>/move-up/", views.bat_move_up, name="bat_move_up"),
    path("bat/<int:pk>/move-down/", views.bat_move_down, name="bat_move_down"),
    # Реестр юридических адресов
    path("bea/table/", views.bea_table_partial, name="bea_table_partial"),
    path("bea/identifier-record-search/", views.bea_identifier_record_search, name="bea_identifier_record_search"),
    path("bea/create/", views.bea_form_create, name="bea_form_create"),
    path("bea/<int:pk>/edit/", views.bea_form_edit, name="bea_form_edit"),
    path("bea/<int:pk>/delete/", views.bea_delete, name="bea_delete"),
    path("bea/<int:pk>/move-up/", views.bea_move_up, name="bea_move_up"),
    path("bea/<int:pk>/move-down/", views.bea_move_down, name="bea_move_down"),
    # Реестр реорганизаций
    path("brl/table/", views.brl_table_partial, name="brl_table_partial"),
    path("brl/business-entity-search/", views.brl_business_entity_search, name="brl_business_entity_search"),
    path("brl/create/", views.brl_form_create, name="brl_form_create"),
    path("brl/<int:pk>/edit/", views.brl_form_edit, name="brl_form_edit"),
    path("brl/<int:pk>/delete/", views.brl_delete, name="brl_delete"),
    path("brl/<int:pk>/move-up/", views.brl_move_up, name="brl_move_up"),
    path("brl/<int:pk>/move-down/", views.brl_move_down, name="brl_move_down"),
    # ОКСМ
    path("oksm/table/", views.oksm_table_partial, name="oksm_table_partial"),
    path("oksm/create/", views.oksm_form_create, name="oksm_form_create"),
    path("oksm/<int:pk>/edit/", views.oksm_form_edit, name="oksm_form_edit"),
    path("oksm/<int:pk>/delete/", views.oksm_delete, name="oksm_delete"),
    path("oksm/<int:pk>/move-up/", views.oksm_move_up, name="oksm_move_up"),
    path("oksm/<int:pk>/move-down/", views.oksm_move_down, name="oksm_move_down"),
    path("oksm/csv-upload/", views.oksm_csv_upload, name="oksm_csv_upload"),
    # ОКВ
    path("okv/table/", views.okv_table_partial, name="okv_table_partial"),
    path("okv/create/", views.okv_form_create, name="okv_form_create"),
    path("okv/<int:pk>/edit/", views.okv_form_edit, name="okv_form_edit"),
    path("okv/<int:pk>/delete/", views.okv_delete, name="okv_delete"),
    path("okv/<int:pk>/move-up/", views.okv_move_up, name="okv_move_up"),
    path("okv/<int:pk>/move-down/", views.okv_move_down, name="okv_move_down"),
    path("okv/csv-upload/", views.okv_csv_upload, name="okv_csv_upload"),
    # Классификатор идентификаторов юрлиц (LEI)
    path("lei/table/", views.lei_table_partial, name="lei_table_partial"),
    path("lei/create/", views.lei_form_create, name="lei_form_create"),
    path("lei/<int:pk>/edit/", views.lei_form_edit, name="lei_form_edit"),
    path("lei/<int:pk>/delete/", views.lei_delete, name="lei_delete"),
    path("lei/<int:pk>/move-up/", views.lei_move_up, name="lei_move_up"),
    path("lei/<int:pk>/move-down/", views.lei_move_down, name="lei_move_down"),
    # Классификатор идентификаторов физлиц (PEI)
    path("pei/table/", views.pei_table_partial, name="pei_table_partial"),
    path("pei/create/", views.pei_form_create, name="pei_form_create"),
    path("pei/<int:pk>/edit/", views.pei_form_edit, name="pei_form_edit"),
    path("pei/<int:pk>/delete/", views.pei_delete, name="pei_delete"),
    path("pei/<int:pk>/move-up/", views.pei_move_up, name="pei_move_up"),
    path("pei/<int:pk>/move-down/", views.pei_move_down, name="pei_move_down"),
    # Классификатор numcap
    path("numcap/table/", views.numcap_table_partial, name="numcap_table_partial"),
    path("numcap/create/", views.numcap_form_create, name="numcap_form_create"),
    path("numcap/<int:pk>/edit/", views.numcap_form_edit, name="numcap_form_edit"),
    path("numcap/<int:pk>/delete/", views.numcap_delete, name="numcap_delete"),
    path("numcap/<int:pk>/move-up/", views.numcap_move_up, name="numcap_move_up"),
    path("numcap/<int:pk>/move-down/", views.numcap_move_down, name="numcap_move_down"),
    path("numcap/csv-upload/", views.numcap_csv_upload, name="numcap_csv_upload"),
    # КАТД
    path("katd/countries-for-date/", views.katd_countries_for_date, name="katd_countries_for_date"),
    path("katd/table/", views.katd_table_partial, name="katd_table_partial"),
    path("katd/create/", views.katd_form_create, name="katd_form_create"),
    path("katd/<int:pk>/edit/", views.katd_form_edit, name="katd_form_edit"),
    path("katd/<int:pk>/delete/", views.katd_delete, name="katd_delete"),
    path("katd/<int:pk>/move-up/", views.katd_move_up, name="katd_move_up"),
    path("katd/<int:pk>/move-down/", views.katd_move_down, name="katd_move_down"),
    path("katd/csv-upload/", views.katd_csv_upload, name="katd_csv_upload"),
    # Коды субъектов Российской Федерации
    path("rfs/table/", views.rfs_table_partial, name="rfs_table_partial"),
    path("rfs/oktmo-for-subject/", views.rfs_oktmo_for_subject, name="rfs_oktmo_for_subject"),
    path("rfs/create/", views.rfs_form_create, name="rfs_form_create"),
    path("rfs/<int:pk>/edit/", views.rfs_form_edit, name="rfs_form_edit"),
    path("rfs/<int:pk>/delete/", views.rfs_delete, name="rfs_delete"),
    path("rfs/<int:pk>/move-up/", views.rfs_move_up, name="rfs_move_up"),
    path("rfs/<int:pk>/move-down/", views.rfs_move_down, name="rfs_move_down"),
    path("rfs/csv-upload/", views.rfs_csv_upload, name="rfs_csv_upload"),
    # Величина прожиточного минимума
    path("lw/table/", views.lw_table_partial, name="lw_table_partial"),
    path("lw/regions/", views.lw_regions_for_country, name="lw_regions_for_country"),
    path("lw/currency/", views.lw_currency_for_country, name="lw_currency_for_country"),
    path("lw/create/", views.lw_form_create, name="lw_form_create"),
    path("lw/<int:pk>/edit/", views.lw_form_edit, name="lw_form_edit"),
    path("lw/<int:pk>/delete/", views.lw_delete, name="lw_delete"),
    path("lw/<int:pk>/move-up/", views.lw_move_up, name="lw_move_up"),
    path("lw/<int:pk>/move-down/", views.lw_move_down, name="lw_move_down"),
    path("lw/csv-upload/", views.lw_csv_upload, name="lw_csv_upload"),
    # Производственный календарь
    path("pc/partial/", views.pc_partial, name="pc_partial"),
    path("pc/table/", views.pc_table_partial, name="pc_table_partial"),
    path("pc/generate/", views.pc_generate, name="pc_generate"),
    path("pc/load-source/", views.pc_load_source, name="pc_load_source"),
    path("pc/create/", views.pc_form_create, name="pc_form_create"),
    path("pc/<int:pk>/edit/", views.pc_form_edit, name="pc_form_edit"),
    path("pc/<int:pk>/delete/", views.pc_delete, name="pc_delete"),
    path("business-registry/csv-download/", views.business_registry_csv_download, name="business_registry_csv_download"),
    path("business-registry/csv-upload/", views.business_registry_csv_upload, name="business_registry_csv_upload"),
    # База юридических лиц (LER)
    path("ler/search/", views.ler_search, name="ler_search"),
    path("ler/identifiers-for-country/", views.ler_identifiers_for_country, name="ler_identifiers_for_country"),
    path("ler/regions-for-country/", views.ler_regions_for_country, name="ler_regions_for_country"),
    path("ler/region-code-for-country/", views.ler_region_code_for_country, name="ler_region_code_for_country"),
    path("ler/region-autofill/", views.ler_region_autofill, name="ler_region_autofill"),
    path("ler/table/", views.ler_table_partial, name="ler_table_partial"),
    path("ler/create/", views.ler_form_create, name="ler_form_create"),
    path("ler/<int:pk>/edit/", views.ler_form_edit, name="ler_form_edit"),
    path("ler/<int:pk>/delete/", views.ler_delete, name="ler_delete"),
    path("ler/<int:pk>/move-up/", views.ler_move_up, name="ler_move_up"),
    path("ler/<int:pk>/move-down/", views.ler_move_down, name="ler_move_down"),
    path("ler/csv-upload/", views.ler_csv_upload, name="ler_csv_upload"),
]
