# Generated by Django 5.2.5 on 2025-10-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docops_queue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="doc_url",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
    ]
