# Generated by Django 5.2.5 on 2025-10-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docops_queue", "0002_alter_job_doc_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="doc_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=512
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["doc_key", "status"], name="docops_queu_doc_key_a59e87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "-priority", "created_at"],
                name="docops_queu_status_783057_idx",
            ),
        ),
    ]
