# Generated by Django 5.2.5 on 2025-10-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docops_queue", "0004_add_indexes_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="trace_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
