# Generated by Django 5.2.5 on 2026-03-26 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_course_id', models.PositiveBigIntegerField(unique=True, verbose_name='ID курса в Moodle')),
                ('shortname', models.CharField(blank=True, default='', max_length=255, verbose_name='Короткое имя')),
                ('fullname', models.CharField(max_length=255, verbose_name='Название курса')),
                ('category_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Категория')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('moodle_url', models.URLField(blank=True, default='', verbose_name='Ссылка на курс')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Доступен пользователям')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные Moodle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Курс обучения',
                'verbose_name_plural': 'Курсы обучения',
                'ordering': ['fullname', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('catalog', 'Каталог'), ('users', 'Пользователи'), ('results', 'Результаты'), ('full', 'Полная синхронизация')], max_length=20, verbose_name='Область синхронизации')),
                ('status', models.CharField(choices=[('started', 'Запущена'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='started', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='Статистика')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Текст ошибки')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='Служебные данные')),
            ],
            options={
                'verbose_name': 'Запуск синхронизации обучения',
                'verbose_name_plural': 'Запуски синхронизации обучения',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LearningUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_user_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='ID пользователя в Moodle')),
                ('moodle_username', models.CharField(blank=True, default='', max_length=255, verbose_name='Логин в Moodle')),
                ('moodle_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email в Moodle')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход в Moodle')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные Moodle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Связка пользователя с Moodle',
                'verbose_name_plural': 'Связки пользователей с Moodle',
            },
        ),
        migrations.CreateModel(
            name='LearningCourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('failed', 'Не пройден')], default='not_started', max_length=32, verbose_name='Статус прохождения')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс, %')),
                ('grade_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Итоговый балл')),
                ('grade_display', models.CharField(blank=True, default='', max_length=100, verbose_name='Отображаемый балл')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('certificate_url', models.URLField(blank=True, default='', verbose_name='Ссылка на сертификат')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные Moodle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='learning_app.learningcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_course_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Результат по курсу',
                'verbose_name_plural': 'Результаты по курсам',
                'ordering': ['-completed_at', '-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='learning_result_user_course_uniq')],
            },
        ),
        migrations.CreateModel(
            name='LearningEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_enrollment_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID назначения в Moodle')),
                ('role_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Роль')),
                ('enrolled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата назначения')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные Moodle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning_app.learningcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Назначение курса',
                'verbose_name_plural': 'Назначения курсов',
                'ordering': ['-enrolled_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='learning_enrollment_user_course_uniq')],
            },
        ),
    ]
