# Generated by Django 5.2.5 on 2026-03-18 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policy_app', '0024_add_expertise_dir_to_typical_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('gph', 'ГПХ Договор гражданско-правового характера'), ('smz', 'СМЗ Договор с самозанятым')], max_length=16, verbose_name='Вид')),
                ('party', models.CharField(choices=[('individual', 'Физлицо'), ('legal_entity', 'Юрлицо')], max_length=16, verbose_name='Сторона')),
                ('country_name', models.CharField(max_length=255, verbose_name='Страна')),
                ('country_code', models.CharField(blank=True, default='', max_length=3, verbose_name='Код страны (ОКСМ)')),
                ('sample_name', models.CharField(max_length=512, verbose_name='Наименование образца')),
                ('version', models.CharField(blank=True, default='', max_length=128, verbose_name='Версия')),
                ('file', models.FileField(blank=True, default='', upload_to='contract_templates/', verbose_name='Файл')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_templates', to='policy_app.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Образец шаблона договора',
                'verbose_name_plural': 'Образцы шаблонов договоров',
                'ordering': ['position', 'id'],
            },
        ),
    ]
