# Generated by Django 5.2.5 on 2026-03-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0003_contractvariable_source_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='is_all_sections',
            field=models.BooleanField(default=True, verbose_name='Все разделы'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='typical_sections_json',
            field=models.JSONField(blank=True, default=list, verbose_name='Типовые разделы (услуги)'),
        ),
    ]
