# Generated by Django 5.2.5 on 2026-03-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0004_contracttemplate_is_all_sections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttemplate',
            name='party',
            field=models.CharField(choices=[('individual', 'ФЗЛ Физлицо'), ('legal_entity', 'ЮРЛ Юрлицо'), ('ip', 'ИП Индивидуальный предприниматель')], max_length=16, verbose_name='Сторона'),
        ),
    ]
