# Generated by Django 5.2.5 on 2026-03-20 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0006_contracttemplate_group_member'),
        ('group_app', '0006_orgunit_expertise_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttemplate',
            name='group_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_templates', to='group_app.groupmember', verbose_name='Группа'),
        ),
    ]
