# Generated by Django 5.2.5 on 2026-03-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts_app", "0007_alter_contracttemplate_group_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractvariable",
            name="is_computed",
            field=models.BooleanField(default=False, verbose_name="Расчётное поле"),
        ),
    ]
