# Generated by Django 5.2.5 on 2026-03-21 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0015_seed_chapters_name_variable'),
        ('policy_app', '0024_add_expertise_dir_to_typical_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_text', models.CharField(blank=True, default='', max_length=1024, verbose_name='Предмет договора')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_subjects', to='policy_app.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Предмет договора',
                'verbose_name_plural': 'Предметы договора',
                'ordering': ['position', 'id'],
            },
        ),
    ]
