# Generated by Django 5.2.5 on 2026-03-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0017_seed_contract_number_and_name_variables'),
        ('projects_app', '0046_add_signed_scan_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractProjectWork',
            fields=[
            ],
            options={
                'verbose_name': 'В работе: Проект договора',
                'verbose_name_plural': 'В работе: Проекты договоров',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects_app.performer',),
        ),
        migrations.CreateModel(
            name='ContractSigningWork',
            fields=[
            ],
            options={
                'verbose_name': 'В работе: Подписание договора',
                'verbose_name_plural': 'В работе: Подписание договоров',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects_app.performer',),
        ),
    ]
