# Generated by Django 5.2.5 on 2026-05-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0031_contract_project_payment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractprojectregistration',
            name='contract_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Номер договора'),
        ),
    ]
