# Generated by Django 5.2.5 on 2026-06-01 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_app', '0041_contract_project_registration_final_report_term_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractprojectregistration',
            name='source_data_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата предоставления данных'),
        ),
        migrations.AddField(
            model_name='contractprojectregistration',
            name='source_data_term',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Исходные данные'),
        ),
        migrations.AddField(
            model_name='contractprojectregistration',
            name='source_data_term_unit',
            field=models.CharField(choices=[('days', 'дн.'), ('weeks', 'нед.'), ('months', 'мес.')], default='weeks', max_length=10, verbose_name='Единица срока предоставления исходных данных'),
        ),
        migrations.AlterField(
            model_name='contractprojectregistration',
            name='final_report_term_weeks',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Итоговый отчёт'),
        ),
        migrations.AlterField(
            model_name='contractprojectregistration',
            name='service_term_months',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Предварительный отчёт'),
        ),
    ]
