# Generated by Django 5.2.5 on 2026-03-06 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='URL-токен')),
                ('code', models.CharField(max_length=6, verbose_name='Код подтверждения')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попытки')),
                ('last_sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Последняя отправка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_registration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ожидающая регистрация',
                'verbose_name_plural': 'Ожидающие регистрации',
            },
        ),
    ]
