# Generated by Django 5.2.5 on 2026-03-14 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_app', '0005_orgunit_short_name'),
        ('users_app', '0004_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, default='', max_length=512, verbose_name='Специальность')),
                ('specialty_en', models.CharField(blank=True, default='', max_length=512, verbose_name='Специальность на англ. языке')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expertise_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_specialties', to='group_app.orgunit', verbose_name='Направление экспертизы')),
                ('head_of_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_specialties', to='users_app.employee', verbose_name='Руководитель направления')),
            ],
            options={
                'verbose_name': 'Специальность эксперта',
                'verbose_name_plural': 'Специальности экспертов',
                'ordering': ['position', 'id'],
            },
        ),
    ]
