# Generated by Django 5.2.5 on 2026-03-14 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers_app', '0013_legalentityrecord'),
        ('experts_app', '0001_initial'),
        ('group_app', '0005_orgunit_short_name'),
        ('policy_app', '0017_create_group_director'),
        ('users_app', '0004_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_email', models.CharField(blank=True, default='', max_length=255, verbose_name='Дополнительная эл. почта')),
                ('extra_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Дополнительный телефон')),
                ('status', models.CharField(blank=True, default='', max_length=255, verbose_name='Статус')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_profiles', to='classifiers_app.oksmcountry', verbose_name='Страна')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to='users_app.employee', verbose_name='Сотрудник')),
                ('expertise_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_profiles', to='group_app.orgunit', verbose_name='Направление экспертизы')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_profiles', to='policy_app.grade', verbose_name='Грейд')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_profiles', to='classifiers_app.territorialdivision', verbose_name='Регион')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_profiles', to='experts_app.expertspecialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Профиль эксперта',
                'verbose_name_plural': 'База экспертов',
                'ordering': ['position', 'id'],
            },
        ),
    ]
