# Generated by Django 5.2.5 on 2026-03-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0002_expertprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertprofile',
            name='specialty',
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='expert_profiles', to='experts_app.expertspecialty', verbose_name='Специальности'),
        ),
    ]
