# Generated by Django 5.2.5 on 2026-03-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0004_expertprofilespecialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertspecialty',
            name='specialty',
            field=models.CharField(blank=True, default='', max_length=512, unique=True, verbose_name='Специальность'),
        ),
    ]
