# Generated by Django 5.2.5 on 2026-03-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0005_alter_expertspecialty_specialty'),
        ('group_app', '0006_orgunit_expertise_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertspecialty',
            name='is_group_owner',
            field=models.BooleanField(default=False, verbose_name='Группа (все компании)'),
        ),
        migrations.AddField(
            model_name='expertspecialty',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='expert_specialties_owned', to='group_app.groupmember', verbose_name='Владельцы'),
        ),
    ]
