# Generated by Django 5.2.5 on 2026-03-17 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0006_expertspecialty_is_group_owner_and_more'),
        ('policy_app', '0021_product_m2m_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertspecialty',
            name='expertise_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_specialties_linked', to='policy_app.expertisedirection', verbose_name='Направление экспертизы (политика)'),
        ),
    ]
