# Generated by Django 5.2.5 on 2026-03-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experts_app", "0007_expertspecialty_expertise_dir"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertprofile",
            name="bank_address",
            field=models.CharField(
                blank=True, default="", max_length=512, verbose_name="Адрес банка"
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="bank_bik",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="БИК"
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="bank_inn",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="ИНН банка"
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="bank_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Наименование банка",
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="bank_swift",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="SWIFT"
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="citizenship",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Гражданство"
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="corr_account",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Кор. счет"
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="corr_bank_bik",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="БИК банка-корреспондента",
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="corr_bank_corr_account",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Кор. счет банка-корреспондента",
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="corr_bank_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Наименование банка-корреспондента",
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="corr_bank_settlement_account",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Рас. счет банка-корреспондента",
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="corr_bank_swift",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="SWIFT банка-корреспондента",
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="full_name_genitive",
            field=models.CharField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="ФИО (полное) родительный падеж",
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Мужской"), ("female", "Женский")],
                default="",
                max_length=10,
                verbose_name="Пол",
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="inn",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="ИНН"
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="passport_division_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Паспорт: код подразделения",
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="passport_expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Паспорт: срок действия"
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="passport_issue_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Паспорт: дата выдачи"
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="passport_issued_by",
            field=models.CharField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Паспорт: кем выдан",
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="passport_number",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Паспорт: номер"
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="passport_series",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Паспорт: серия"
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="registration_address",
            field=models.CharField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Регистрация: адрес",
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="self_employed",
            field=models.BooleanField(default=False, verbose_name="Само-занятость"),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="settlement_account",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Рас. счет"
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="snils",
            field=models.DateField(blank=True, null=True, verbose_name="СНИЛС"),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="tax_rate",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Ставка налога, %"
            ),
        ),
    ]
