# Generated by Django 5.2.5 on 2026-02-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255, verbose_name='Наименование компании (краткое)')),
                ('full_name', models.CharField(blank=True, default='', max_length=512, verbose_name='Наименование компании (полное)')),
                ('name_en', models.CharField(blank=True, default='', max_length=512, verbose_name='Наименование на английском языке')),
                ('country_name', models.CharField(max_length=255, verbose_name='Страна регистрации')),
                ('country_code', models.CharField(blank=True, default='', max_length=3, verbose_name='Код страны (ОКСМ)')),
                ('identifier', models.CharField(blank=True, default='', max_length=255, verbose_name='Идентификатор')),
                ('registration_number', models.CharField(blank=True, default='', max_length=255, verbose_name='Регистрационный номер')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Участник группы',
                'verbose_name_plural': 'Состав группы',
                'ordering': ['position', 'id'],
            },
        ),
    ]
