# Generated by Django 5.2.5 on 2026-03-17 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0005_orgunit_short_name'),
        ('policy_app', '0021_product_m2m_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunit',
            name='expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_units', to='policy_app.expertisedirection', verbose_name='Экспертиза'),
        ),
    ]
