# Generated by Django 5.2.5 on 2025-08-30 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onedrive_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OneDriveSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drive_id", models.CharField(blank=True, max_length=128)),
                ("item_id", models.CharField(blank=True, max_length=256)),
                ("item_name", models.CharField(blank=True, max_length=512)),
                ("item_path", models.CharField(blank=True, max_length=1024)),
                ("web_url", models.URLField(blank=True)),
                ("is_folder", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onedrive_selection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
