# Generated by Django 5.2.5 on 2025-08-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onedrive_app", "0002_onedriveselection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="textentry",
            name="user",
        ),
        migrations.DeleteModel(
            name="DocumentBinding",
        ),
        migrations.DeleteModel(
            name="TextEntry",
        ),
    ]
