# Generated by Django 5.2.5 on 2025-09-19 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy_app", "0005_alter_typicalsection_options"),
        ("requests_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="policy_app.product",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="policy_app.typicalsection",
                        verbose_name="Раздел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Таблица запросов",
                "verbose_name_plural": "Таблицы запросов",
                "ordering": ["product__position", "section__position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Позиция"
                    ),
                ),
                ("code", models.CharField(max_length=32, verbose_name="Код")),
                ("number", models.PositiveIntegerField(default=0, verbose_name="№")),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование запроса"
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="requests_app.requesttable",
                        verbose_name="Таблица",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос",
                "verbose_name_plural": "Запросы",
                "ordering": ["position", "id"],
            },
        ),
        migrations.DeleteModel(
            name="RequestItem",
        ),
        migrations.AddConstraint(
            model_name="requesttable",
            constraint=models.UniqueConstraint(
                fields=("product", "section"), name="ux_request_table_product_section"
            ),
        ),
    ]
