# Generated by Django 5.2.5 on 2025-09-19 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy_app", "0005_alter_typicalsection_options"),
        ("requests_app", "0002_requesttable_request_delete_requestitem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requesttable",
            name="product",
        ),
        migrations.RemoveField(
            model_name="requesttable",
            name="section",
        ),
        migrations.CreateModel(
            name="RequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Позиция"
                    ),
                ),
                ("code", models.CharField(max_length=64, verbose_name="Код")),
                (
                    "number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="№"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование запроса"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_items",
                        to="policy_app.product",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_items",
                        to="policy_app.typicalsection",
                        verbose_name="Раздел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос",
                "verbose_name_plural": "Запросы",
                "ordering": [
                    "product__position",
                    "section__position",
                    "position",
                    "id",
                ],
            },
        ),
        migrations.DeleteModel(
            name="Request",
        ),
        migrations.DeleteModel(
            name="RequestTable",
        ),
        migrations.AddConstraint(
            model_name="requestitem",
            constraint=models.UniqueConstraint(
                fields=("product", "section", "code"),
                name="ux_requestitem_product_section_code",
            ),
        ),
    ]
