# Generated by Django 5.2.5 on 2025-09-20 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy_app", "0005_alter_typicalsection_options"),
        ("requests_app", "0003_remove_requesttable_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Таблица запросов",
                "verbose_name_plural": "Таблицы запросов",
            },
        ),
        migrations.AlterModelOptions(
            name="requestitem",
            options={
                "ordering": ["position", "id"],
                "verbose_name": "Запрос",
                "verbose_name_plural": "Запросы",
            },
        ),
        migrations.RemoveConstraint(
            model_name="requestitem",
            name="ux_requestitem_product_section_code",
        ),
        migrations.RemoveField(
            model_name="requestitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="requestitem",
            name="section",
        ),
        migrations.AlterField(
            model_name="requestitem",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="requestitem",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="requestitem",
            name="number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="requestitem",
            name="position",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="requesttable",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_tables",
                to="policy_app.product",
            ),
        ),
        migrations.AddField(
            model_name="requesttable",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_tables",
                to="policy_app.typicalsection",
            ),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='table',
            field=models.ForeignKey(
                to='requests_app.requesttable',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='items',
                null=True, blank=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requesttable",
            unique_together={("product", "section")},
        ),
    ]
