# Generated by Django 5.2.5 on 2025-09-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0006_requestitem_table_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestitem",
            name="short_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                verbose_name="Краткое наименование",
            ),
        ),
    ]
