# Generated by Django 5.2.5 on 2026-03-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0007_requestitem_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='name',
            field=models.TextField(verbose_name='Наименование запроса'),
        ),
    ]
