from __future__ import annotations


PROPOSAL_REGISTRY_UI_COLUMNS = [
    {
        "picker_value": "number",
        "data_col": "number",
        "source_column": "number",
        "label": "Номер",
        "variable_available": True,
    },
    {
        "picker_value": "group",
        "data_col": "group",
        "source_column": "group",
        "label": "Группа",
        "variable_available": True,
    },
    {
        "picker_value": "tkp-id",
        "data_col": "tkp-id",
        "source_column": "tkp_id",
        "label": "ТКП ID",
        "variable_available": True,
    },
    {
        "picker_value": "type",
        "data_col": "type",
        "source_column": "type",
        "label": "Тип",
        "variable_available": True,
    },
    {
        "picker_value": "name",
        "data_col": "name",
        "source_column": "name",
        "label": "Название",
        "variable_available": True,
    },
    {
        "picker_value": "kind",
        "data_col": "kind",
        "source_column": "kind",
        "label": "Вид",
        "variable_available": True,
    },
    {
        "picker_value": "status",
        "data_col": "status",
        "source_column": "status",
        "label": "Статус",
        "variable_available": True,
    },
    {
        "picker_value": "year",
        "data_col": "year",
        "source_column": "year",
        "label": "Год",
        "variable_available": True,
    },
    {
        "picker_value": "customer",
        "data_col": "customer",
        "source_column": "customer",
        "label": "Заказчик: наименование",
        "split_prefix": "Заказчик: ",
        "split_suffix": "наименование",
        "split_inline": True,
        "variable_available": True,
    },
    {
        "picker_value": "country",
        "data_col": "country",
        "source_column": "country",
        "label": "Заказчик: страна",
        "split_prefix": "Заказчик: ",
        "split_suffix": "страна",
        "variable_available": True,
    },
    {
        "picker_value": "identifier",
        "data_col": "identifier",
        "source_column": "identifier",
        "label": "Заказчик: идент.",
        "split_prefix": "Заказчик: ",
        "split_suffix": "идент.",
        "variable_available": True,
    },
    {
        "picker_value": "reg-number",
        "data_col": "reg-number",
        "source_column": "registration_number",
        "label": "Заказчик: регистр. номер",
        "split_prefix": "Заказчик: ",
        "split_suffix": "регистр. номер",
        "variable_available": True,
    },
    {
        "picker_value": "region",
        "data_col": "region",
        "source_column": "registration_region",
        "label": "Заказчик: регион",
        "split_prefix": "Заказчик: ",
        "split_suffix": "регион",
        "variable_available": True,
    },
    {
        "picker_value": "date",
        "data_col": "date",
        "source_column": "date",
        "label": "Заказчик: дата регистр.",
        "split_prefix": "Заказчик: ",
        "split_suffix": "дата регистр.",
        "variable_available": True,
    },
    {
        "picker_value": "asset-owner",
        "data_col": "asset-owner",
        "source_column": "asset_owner",
        "label": "Владелец: наименование",
        "split_prefix": "Владелец: ",
        "split_suffix": "наименование",
        "split_inline": True,
        "variable_available": True,
    },
    {
        "picker_value": "asset-owner-country",
        "data_col": "asset-owner-country",
        "source_column": "asset_owner_country",
        "label": "Владелец: страна",
        "split_prefix": "Владелец: ",
        "split_suffix": "страна",
        "variable_available": True,
    },
    {
        "picker_value": "asset-owner-identifier",
        "data_col": "asset-owner-identifier",
        "source_column": "asset_owner_identifier",
        "label": "Владелец: идент.",
        "split_prefix": "Владелец: ",
        "split_suffix": "идент.",
        "variable_available": True,
    },
    {
        "picker_value": "asset-owner-reg-number",
        "data_col": "asset-owner-reg-number",
        "source_column": "asset_owner_registration_number",
        "label": "Владелец: регистр. номер",
        "split_prefix": "Владелец: ",
        "split_suffix": "регистр. номер",
        "variable_available": True,
    },
    {
        "picker_value": "asset-owner-region",
        "data_col": "asset-owner-region",
        "source_column": "asset_owner_region",
        "label": "Владелец: регион",
        "split_prefix": "Владелец: ",
        "split_suffix": "регион",
        "variable_available": True,
    },
    {
        "picker_value": "asset-owner-date",
        "data_col": "asset-owner-date",
        "source_column": "asset_owner_registration_date",
        "label": "Владелец: дата регистр.",
        "split_prefix": "Владелец: ",
        "split_suffix": "дата регистр.",
        "variable_available": True,
    },
    {
        "picker_value": "proposal-project-name",
        "data_col": "proposal-project-name",
        "source_column": "proposal_project_name",
        "label": "Наименование ТКП (проекта)",
        "variable_available": True,
    },
    {
        "picker_value": "purpose",
        "data_col": "purpose",
        "source_column": "purpose",
        "label": "Цель",
        "variable_available": True,
    },
    {
        "picker_value": "service-composition",
        "data_col": "service-composition",
        "source_column": "service_composition",
        "label": "Состав услуг",
        "variable_available": True,
    },
    {
        "picker_value": "evaluation-date",
        "data_col": "evaluation-date",
        "source_column": "evaluation_date",
        "label": "Дата оценки",
        "variable_available": True,
    },
    {
        "picker_value": "term",
        "data_col": "term",
        "source_column": "term",
        "label": "Срок",
        "variable_available": True,
    },
    {
        "picker_value": "preliminary-report-date",
        "data_col": "preliminary-report-date",
        "source_column": "preliminary_report_date",
        "label": "Дата предв. отчёта",
        "variable_available": True,
    },
    {
        "picker_value": "final-report-date",
        "data_col": "final-report-date",
        "source_column": "final_report_date",
        "label": "Дата итог. отчёта",
        "variable_available": True,
    },
    {
        "picker_value": "report-languages",
        "data_col": "report-languages",
        "source_column": "report_languages",
        "label": "Языки отчёта",
        "variable_available": True,
    },
    {
        "picker_value": "service-cost",
        "data_col": "service-cost",
        "source_column": "service_cost",
        "label": "Стоимость услуг",
        "variable_available": True,
    },
    {
        "picker_value": "currency",
        "data_col": "currency",
        "source_column": "currency",
        "label": "Валюта",
        "variable_available": True,
    },
    {
        "picker_value": "advance-percent",
        "data_col": "advance-percent",
        "source_column": "advance_percent",
        "label": "Предоплата, проц.",
        "variable_available": True,
    },
    {
        "picker_value": "advance-term",
        "data_col": "advance-term",
        "source_column": "advance_term",
        "label": "Предоплата, срок",
        "variable_available": True,
    },
    {
        "picker_value": "preliminary-report-percent",
        "data_col": "preliminary-report-percent",
        "source_column": "preliminary_report_percent",
        "label": "Предв. отчёт, проц.",
        "variable_available": True,
    },
    {
        "picker_value": "preliminary-report-term",
        "data_col": "preliminary-report-term",
        "source_column": "preliminary_report_term",
        "label": "Предв. отчёт, срок",
        "variable_available": True,
    },
    {
        "picker_value": "final-report-percent",
        "data_col": "final-report-percent",
        "source_column": "final_report_percent",
        "label": "Итог. отчёт, проц.",
        "variable_available": True,
    },
    {
        "picker_value": "final-report-term",
        "data_col": "final-report-term",
        "source_column": "final_report_term",
        "label": "Итог. отчёт, срок",
        "variable_available": True,
    },
]


def get_proposal_registry_ui_columns():
    return [dict(item) for item in PROPOSAL_REGISTRY_UI_COLUMNS]


def get_proposal_registry_variable_columns():
    columns = {
        item["source_column"]: item["label"]
        for item in PROPOSAL_REGISTRY_UI_COLUMNS
        if item.get("variable_available", True)
    }
    # Keep the legacy source column available so old non-computed variables
    # bound before the computed-variable migration can still be edited/saved.
    columns.setdefault("country_full_name", "Наименование страны (полное)")
    return columns
