# Generated by Django 5.2.5 on 2025-11-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockseditor_app", "0001_block_nodes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blocknode",
            options={
                "ordering": ["display_order", "pk"],
                "verbose_name": "Узел редактора",
                "verbose_name_plural": "Узлы редактора",
            },
        ),
        migrations.AlterField(
            model_name="blocknode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
