# Generated by Django 5.2.5 on 2025-08-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="block",
            options={},
        ),
        migrations.RemoveField(
            model_name="block",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="block",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="block",
            name="model",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="block",
            name="code",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="block",
            name="context",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="block",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="block",
            name="prompt",
            field=models.TextField(),
        ),
    ]
