# Generated by Django 5.2.5 on 2025-08-31 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks_app", "0002_alter_block_options_remove_block_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="block",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Блок",
                "verbose_name_plural": "Блоки",
            },
        ),
        migrations.AddField(
            model_name="block",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Создано",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="block",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="block",
            name="code",
            field=models.CharField(
                db_index=True, max_length=100, unique=True, verbose_name="Код блока"
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="context",
            field=models.TextField(blank=True, default="", verbose_name="Контекст"),
        ),
        migrations.AlterField(
            model_name="block",
            name="model",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Модель"
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Наименование блока"),
        ),
        migrations.AlterField(
            model_name="block",
            name="prompt",
            field=models.TextField(verbose_name="Промпт"),
        ),
    ]
