# Generated by Django 5.2.5 on 2025-09-05 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks_app", "0003_alter_block_options_block_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="temperature",
            field=models.FloatField(
                blank=True,
                help_text="Оставьте пустым — будет значение по умолчанию модели.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(2.0),
                ],
                verbose_name="Температура",
            ),
        ),
    ]
