# Generated by Django 5.2.5 on 2025-09-08 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks_app", "0004_add_temperature_field"),
        ("policy_app", "0002_typicalsection"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocks",
                to="policy_app.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocks",
                to="policy_app.typicalsection",
                verbose_name="Раздел",
            ),
        ),
    ]
