# Generated by Django 5.2.5 on 2025-11-23 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policy_app", "0005_alter_typicalsection_options"),
        ("projects_app", "0014_alter_projectregistration_short_uid_and_more"),
        ("requests_app", "0007_requestitem_short_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provided", "Предоставлено"),
                            ("partial", "Предоставлено частично"),
                            ("missing", "Не предоставлено"),
                            ("na", "Не требуется"),
                        ],
                        default="missing",
                        max_length=32,
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата изменения статуса"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_statuses",
                        to="projects_app.legalentity",
                    ),
                ),
                (
                    "request_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_statuses",
                        to="requests_app.requestitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус запроса",
                "verbose_name_plural": "Статусы запросов",
                "unique_together": {("request_item", "legal_entity")},
            },
        ),
        migrations.CreateModel(
            name="ChecklistStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("provided", "Предоставлено"),
                            ("partial", "Предоставлено частично"),
                            ("missing", "Не предоставлено"),
                            ("na", "Не требуется"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("provided", "Предоставлено"),
                            ("partial", "Предоставлено частично"),
                            ("missing", "Не предоставлено"),
                            ("na", "Не требуется"),
                        ],
                        max_length=32,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_status_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checklist_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="checklists_app.checkliststatus",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects_app.legalentity",
                    ),
                ),
                (
                    "request_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requests_app.requestitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "История статуса",
                "verbose_name_plural": "История статусов",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistRequestNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Актив"
                    ),
                ),
                (
                    "imc_comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Комментарий IMC Montan"
                    ),
                ),
                (
                    "customer_comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Комментарий Заказчика"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_notes",
                        to="projects_app.projectregistration",
                    ),
                ),
                (
                    "request_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_notes",
                        to="requests_app.requestitem",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_notes",
                        to="policy_app.typicalsection",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий для запроса",
                "verbose_name_plural": "Комментарии для запросов",
                "unique_together": {
                    ("request_item", "project", "section", "asset_name")
                },
            },
        ),
    ]
