# Generated by Django 5.2.5 on 2026-03-04 20:39

import checklists_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists_app', '0002_checklistcommenthistory'),
        ('projects_app', '0014_alter_projectregistration_short_uid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedChecklistLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=checklists_app.models._generate_token, max_length=128, unique=True)),
                ('permission', models.CharField(choices=[('view', 'Доступен просмотр'), ('edit', 'Доступно редактирование')], default='edit', max_length=16)),
                ('expires_at', models.DateTimeField(default=checklists_app.models._default_expiry, verbose_name='Дата прекращения действия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_checklist_links', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_checklist_links', to='projects_app.projectregistration')),
            ],
            options={
                'verbose_name': 'Публичная ссылка на чек-лист',
                'verbose_name_plural': 'Публичные ссылки на чек-листы',
            },
        ),
    ]
