# Generated by Django 5.2.5 on 2026-03-04 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists_app', '0003_add_shared_checklist_link'),
        ('policy_app', '0013_add_product_display_name'),
        ('projects_app', '0014_alter_projectregistration_short_uid_and_more'),
        ('requests_app', '0008_alter_requestitem_name_to_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkliststatushistory',
            name='request_item',
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('number', models.PositiveIntegerField(verbose_name='№')),
                ('short_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Краткое наименование')),
                ('name', models.TextField(verbose_name='Наименование запроса')),
                ('position', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='projects_app.projectregistration')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='policy_app.typicalsection')),
                ('source_request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_checklist_items', to='requests_app.requestitem')),
            ],
            options={
                'verbose_name': 'Пункт чек-листа',
                'verbose_name_plural': 'Пункты чек-листа',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='checklistrequestnote',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='checkliststatus',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='checklistrequestnote',
            name='checklist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='checklists_app.checklistitem'),
        ),
        migrations.AddField(
            model_name='checkliststatus',
            name='checklist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='checklists_app.checklistitem'),
        ),
        migrations.AddField(
            model_name='checkliststatushistory',
            name='checklist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='checklists_app.checklistitem'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistrequestnote',
            unique_together={('checklist_item', 'project', 'section', 'asset_name')},
        ),
        migrations.AlterUniqueTogether(
            name='checkliststatus',
            unique_together={('checklist_item', 'legal_entity')},
        ),
        migrations.RemoveField(
            model_name='checklistrequestnote',
            name='request_item',
        ),
        migrations.RemoveField(
            model_name='checkliststatus',
            name='request_item',
        ),
    ]
