# Generated by Django 5.2.5 on 2026-03-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists_app', '0004_add_checklist_item_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='additional_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доп. запроса'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='additional_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='№ доп. запроса'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='item_type',
            field=models.CharField(choices=[('basic', 'Основной'), ('additional', 'Дополнительный')], default='basic', max_length=16, verbose_name='Тип запроса'),
        ),
    ]
