# Generated by Django 5.2.5 on 2026-03-09 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists_app', '0005_add_item_type_fields'),
        ('projects_app', '0019_performer_info_approval_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItemFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_path', models.CharField(max_length=2048, verbose_name='Путь на диске')),
                ('file_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во файлов')),
                ('last_upload_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя загрузка')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yadisk_folder', to='checklists_app.checklistitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yadisk_folders', to='projects_app.projectregistration')),
            ],
            options={
                'verbose_name': 'Папка пункта чек-листа',
                'verbose_name_plural': 'Папки пунктов чек-листа',
            },
        ),
        migrations.CreateModel(
            name='ProjectWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_path', models.CharField(max_length=2048, verbose_name='Путь на диске')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yadisk_workspace', to='projects_app.projectregistration')),
            ],
            options={
                'verbose_name': 'Рабочее пространство проекта',
                'verbose_name_plural': 'Рабочие пространства проектов',
            },
        ),
    ]
