# Generated by Django 5.2.5 on 2026-03-16 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists_app', '0007_add_customer_status'),
        ('policy_app', '0018_alter_typicalsection_executor_and_more'),
        ('projects_app', '0034_sourcedatatargetfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitemfolder',
            name='public_url',
            field=models.URLField(blank=True, default='', verbose_name='Публичная ссылка'),
        ),
        migrations.CreateModel(
            name='SourceDataItemFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Наименование актива')),
                ('disk_path', models.CharField(max_length=2048, verbose_name='Путь на диске')),
                ('public_url', models.URLField(blank=True, default='', verbose_name='Публичная ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_data_folders', to='checklists_app.checklistitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_data_item_folders', to='projects_app.projectregistration')),
            ],
            options={
                'verbose_name': 'Папка запроса исходных данных',
                'verbose_name_plural': 'Папки запросов исходных данных',
            },
        ),
        migrations.CreateModel(
            name='SourceDataSectionFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Наименование актива')),
                ('disk_path', models.CharField(max_length=2048, verbose_name='Путь на диске')),
                ('public_url', models.URLField(blank=True, default='', verbose_name='Публичная ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_data_section_folders', to='projects_app.projectregistration')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_data_folders', to='policy_app.typicalsection')),
            ],
            options={
                'verbose_name': 'Папка раздела исходных данных',
                'verbose_name_plural': 'Папки разделов исходных данных',
            },
        ),
    ]
