# Generated by Django 5.2.5 on 2026-03-16 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists_app', '0008_checklistitemfolder_public_url_sourcedataitemfolder_and_more'),
        ('projects_app', '0034_sourcedatatargetfolder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedataitemfolder',
            name='file_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во файлов'),
        ),
        migrations.AddField(
            model_name='sourcedataitemfolder',
            name='last_upload_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя загрузка'),
        ),
        migrations.AddField(
            model_name='sourcedataitemfolder',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация'),
        ),
        migrations.AddField(
            model_name='sourcedatasectionfolder',
            name='file_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во файлов'),
        ),
        migrations.AddField(
            model_name='sourcedatasectionfolder',
            name='last_upload_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя загрузка'),
        ),
        migrations.AddField(
            model_name='sourcedatasectionfolder',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация'),
        ),
        migrations.CreateModel(
            name='SourceDataWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_path', models.CharField(max_length=2048, verbose_name='Путь на диске')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_source_data_workspaces', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_data_workspace', to='projects_app.projectregistration')),
            ],
            options={
                'verbose_name': 'Пространство исходных данных',
                'verbose_name_plural': 'Пространства исходных данных',
            },
        ),
    ]
