# Generated by Django 5.2.5 on 2026-03-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists_app', '0009_sourcedataitemfolder_file_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectworkspace',
            name='public_url',
            field=models.URLField(blank=True, default='', verbose_name='Публичная ссылка'),
        ),
    ]
