# Generated by Django 5.2.5 on 2026-03-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists_app', '0010_projectworkspace_public_url'),
        ('policy_app', '0018_alter_typicalsection_executor_and_more'),
        ('projects_app', '0034_sourcedatatargetfolder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sourcedataitemfolder',
            unique_together={('project', 'checklist_item', 'asset_name')},
        ),
        migrations.AlterUniqueTogether(
            name='sourcedatasectionfolder',
            unique_together={('project', 'section', 'asset_name')},
        ),
    ]
