# Generated by Django 5.2.5 on 2026-07-03 14:31

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists_app', '0013_checklistitem_soft_delete_audit'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='checklistitem',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
