# Generated by Django 5.2.5 on 2026-09-15 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists_app', '0014_alter_checklistitem_managers'),
        ('policy_app', '0049_reportstructure'),
        ('projects_app', '0081_resequence_project_stages_by_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSortRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Актив')),
                ('inbox_section_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Каталог inbox')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('done', 'Готово'), ('error', 'Ошибка')], db_index=True, default='queued', max_length=16, verbose_name='Статус')),
                ('workspace_path', models.CharField(blank=True, default='', max_length=2048, verbose_name='Workspace')),
                ('raw_response', models.TextField(blank=True, default='', verbose_name='Ответ DSH')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_sort_runs', to='projects_app.projectregistration')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_sort_runs', to='policy_app.typicalsection')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_sort_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогон сортировки чек-листа',
                'verbose_name_plural': 'Прогоны сортировки чек-листа',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistSortProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_path', models.CharField(max_length=2048, verbose_name='Путь inbox')),
                ('file_count', models.PositiveIntegerField(default=0, verbose_name='Файлов')),
                ('dest_path', models.CharField(blank=True, default='', max_length=2048, verbose_name='Путь dest')),
                ('request_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Наименование запроса')),
                ('quote', models.TextField(blank=True, default='', verbose_name='Цитата')),
                ('confidence', models.CharField(blank=True, default='', max_length=32, verbose_name='Уверенность')),
                ('action', models.CharField(blank=True, default='review', max_length=32, verbose_name='Действие')),
                ('position', models.PositiveIntegerField(default=1)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='checklists_app.checklistsortrun')),
            ],
            options={
                'verbose_name': 'Предложение сортировки',
                'verbose_name_plural': 'Предложения сортировки',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='checklistsortrun',
            index=models.Index(fields=['project', 'section', 'asset_name', '-id'], name='checklists__project_68f5cf_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistsortrun',
            index=models.Index(fields=['status'], name='checklists__status_2732dc_idx'),
        ),
    ]
