# Generated by Django 5.2.5 on 2026-09-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists_app', '0015_checklist_sort_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistsortrun',
            name='local_inbox_path',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Локальный inbox'),
        ),
        migrations.AddField(
            model_name='checklistsortrun',
            name='source_kind',
            field=models.CharField(choices=[('cloud', 'Облако'), ('local', 'Локальная папка')], default='cloud', max_length=16, verbose_name='Источник inbox'),
        ),
    ]
