# Generated by Django 5.2.5 on 2026-09-18 08:10

import django.db.models.deletion
from django.db import migrations, models


def backfill_kit_keys(apps, schema_editor):
    Proposal = apps.get_model("checklists_app", "ChecklistSortProposal")
    for proposal in Proposal.objects.only("id", "kit_path").iterator(chunk_size=500):
        key = "/".join(
            part
            for part in str(proposal.kit_path or "").replace("\\", "/").strip("/").casefold().split("/")
            if part
        )
        Proposal.objects.filter(pk=proposal.pk).update(kit_key=key)


class Migration(migrations.Migration):

    dependencies = [
        ('checklists_app', '0019_checklistsortproposal_verify_started_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSortWorkerState',
            fields=[
                ('key', models.CharField(default='default', max_length=32, primary_key=True, serialize=False)),
                ('worker_id', models.CharField(blank=True, default='', max_length=128)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Состояние worker сортировки',
                'verbose_name_plural': 'Состояния worker сортировки',
            },
        ),
        migrations.AddField(
            model_name='checklistsortproposal',
            name='kit_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2048),
        ),
        migrations.RunPython(backfill_kit_keys, migrations.RunPython.noop),
        migrations.AddField(
            model_name='checklistsortproposal',
            name='verify_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistsortproposal',
            name='verify_lease_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistsortproposal',
            name='verify_worker_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='checklistsortrun',
            name='chunks_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checklistsortrun',
            name='chunks_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checklistsortrun',
            name='deterministic_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checklistsortrun',
            name='fallback_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checklistsortrun',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistsortrun',
            name='kits_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checklistsortrun',
            name='kits_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checklistsortrun',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistsortrun',
            name='worker_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='checklistsortrun',
            name='status',
            field=models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('done', 'Готово'), ('partial', 'Готово частично'), ('error', 'Ошибка')], db_index=True, default='queued', max_length=16, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ChecklistSortChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('deterministic', 'Точное сопоставление'), ('dsh', 'DSH')], default='dsh', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('done', 'Готово'), ('error', 'Ошибка'), ('split', 'Разделён')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('input_kits', models.JSONField(blank=True, default=list)),
                ('result_rows', models.JSONField(blank=True, default=list)),
                ('raw_response', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='checklists_app.checklistsortchunk')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='checklists_app.checklistsortrun')),
            ],
            options={
                'ordering': ['order_key', 'id'],
            },
        ),
        migrations.AddField(
            model_name='checklistsortproposal',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='checklists_app.checklistsortchunk'),
        ),
        migrations.AddIndex(
            model_name='checklistsortchunk',
            index=models.Index(fields=['run', 'status'], name='checklists__run_id_da1d3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistsortchunk',
            constraint=models.UniqueConstraint(fields=('run', 'order_key'), name='uniq_sort_chunk_order'),
        ),
    ]
