# Generated by Django 5.2.5 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts_app", "0003_backfill_person_citizenships"),
    ]

    operations = [
        migrations.AddField(
            model_name="personrecord",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
    ]
