# Generated by Django 5.2.5 on 2025-10-19 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARN", "Warn"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("phase", models.CharField(db_index=True, max_length=64)),
                ("event", models.CharField(db_index=True, max_length=128)),
                ("message", models.TextField(blank=True)),
                ("email", models.CharField(blank=True, max_length=320)),
                (
                    "trace_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("request_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("job_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("via", models.CharField(blank=True, max_length=16)),
                ("project_code6", models.CharField(blank=True, max_length=16)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("section", models.CharField(blank=True, max_length=64)),
                ("anchor_text", models.CharField(blank=True, max_length=256)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("doc_url", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="logs_app_lo_created_316c7d_idx"
                    ),
                    models.Index(
                        fields=["trace_id", "phase"],
                        name="logs_app_lo_trace_i_c57681_idx",
                    ),
                    models.Index(
                        fields=["job_id"], name="logs_app_lo_job_id_100e97_idx"
                    ),
                ],
            },
        ),
    ]
