# Generated by Django 5.2.5 on 2025-11-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="logevent",
            old_name="project_code6",
            new_name="project_uid",
        ),
    ]
