# Generated by Django 5.2.5 on 2025-09-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Краткое имя"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, verbose_name="Наименование на английском языке"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, verbose_name="Наименование на русском языке"
                    ),
                ),
                (
                    "service_type",
                    models.CharField(max_length=128, verbose_name="Тип услуги"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["short_name"],
            },
        ),
    ]
