# Generated by Django 5.2.5 on 2025-09-07 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypicalSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, verbose_name="Код")),
                (
                    "short_name",
                    models.CharField(max_length=64, verbose_name="Краткое имя"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255,
                        verbose_name="Наименование раздела на английском языке",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255,
                        verbose_name="Наименование раздела на русском языке",
                    ),
                ),
                (
                    "accounting_type",
                    models.CharField(max_length=128, verbose_name="Тип учета"),
                ),
                (
                    "executor",
                    models.CharField(max_length=128, verbose_name="Исполнитель"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="policy_app.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Типовой раздел",
                "verbose_name_plural": "Типовые разделы",
                "ordering": ["product__short_name", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "code"), name="ux_section_product_code"
                    )
                ],
            },
        ),
    ]
