# Generated by Django 5.2.5 on 2025-09-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy_app", "0002_typicalsection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["position", "id"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="position",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Позиция"
            ),
        ),
    ]
