# Generated by Django 5.2.5 on 2025-09-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("policy_app", "0004_typicalsection_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="typicalsection",
            options={
                "ordering": ["product__short_name", "position", "id"],
                "verbose_name": "Типовой раздел",
                "verbose_name_plural": "Типовые разделы",
            },
        ),
    ]
