# Generated by Django 5.2.5 on 2026-02-26 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0005_alter_typicalsection_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsections', models.TextField(blank=True, default='', verbose_name='Подразделы')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='policy_app.product', verbose_name='Продукт')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='policy_app.typicalsection', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Типовая структура раздела',
                'verbose_name_plural': 'Типовая структура раздела',
                'ordering': ['position', 'id'],
            },
        ),
    ]
