# Generated by Django 5.2.5 on 2026-02-28 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0007_create_group_department_head'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_en', models.CharField(max_length=255, verbose_name='Грейд на английском языке')),
                ('grade_ru', models.CharField(max_length=255, verbose_name='Грейд на русском языке')),
                ('qualification_levels', models.PositiveIntegerField(default=5, verbose_name='Число уровней квалификации')),
                ('qualification', models.PositiveIntegerField(default=0, verbose_name='Квалификация')),
                ('is_base_rate', models.BooleanField(default=False, verbose_name='Базовая ставка')),
                ('base_rate_share', models.IntegerField(default=0, verbose_name='Доля базовой ставки, %')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Грейд',
                'verbose_name_plural': 'Грейды',
                'ordering': ['position', 'id'],
            },
        ),
    ]
