# Generated by Django 5.2.5 on 2026-02-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0008_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['created_by', 'position', 'id'], 'verbose_name': 'Грейд', 'verbose_name_plural': 'Грейды'},
        ),
    ]
