# Generated by Django 5.2.5 on 2026-02-28 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0009_alter_grade_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate_vpm', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая ставка в ВПМ')),
                ('recommended_specialist', models.CharField(blank=True, default='', max_length=255, verbose_name='Рекомендуемый специалист')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='policy_app.product', verbose_name='Продукт')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='policy_app.typicalsection', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['created_by', 'position', 'id'],
            },
        ),
    ]
