# Generated by Django 5.2.5 on 2026-02-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0010_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='base_rate_vpm',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Базовая ставка в ВПМ'),
        ),
    ]
