# Generated by Django 5.2.5 on 2026-03-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0011_alter_tariff_base_rate_vpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='typicalsection',
            name='short_name_ru',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Краткое имя RU'),
        ),
        migrations.AlterField(
            model_name='typicalsection',
            name='accounting_type',
            field=models.CharField(choices=[('Раздел', 'Раздел'), ('Услуги', 'Услуги')], default='Раздел', max_length=128, verbose_name='Тип учета'),
        ),
        migrations.AlterField(
            model_name='typicalsection',
            name='short_name',
            field=models.CharField(max_length=64, verbose_name='Краткое имя EN'),
        ),
    ]
