# Generated by Django 5.2.5 on 2026-03-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0012_add_short_name_ru_and_accounting_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Отображаемое в системе имя'),
        ),
    ]
