# Generated by Django 5.2.5 on 2026-03-14 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0004_expertprofilespecialty_and_more'),
        ('policy_app', '0017_create_group_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typicalsection',
            name='executor',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Исполнитель'),
        ),
        migrations.CreateModel(
            name='TypicalSectionSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=1, verbose_name='Ранг')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_specialties', to='policy_app.typicalsection')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_links', to='experts_app.expertspecialty')),
            ],
            options={
                'verbose_name': 'Специальность раздела',
                'verbose_name_plural': 'Специальности раздела',
                'ordering': ['rank'],
                'unique_together': {('section', 'specialty')},
            },
        ),
        migrations.AddField(
            model_name='typicalsection',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='typical_sections', through='policy_app.TypicalSectionSpecialty', to='experts_app.expertspecialty', verbose_name='Специальности'),
        ),
    ]
