# Generated by Django 5.2.5 on 2026-03-17 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0005_orgunit_short_name'),
        ('policy_app', '0018_alter_typicalsection_executor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование направления')),
                ('short_name', models.CharField(max_length=128, verbose_name='Краткое обозначение')),
                ('is_group_owner', models.BooleanField(default=False, verbose_name='Группа (все компании)')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expertise_directions', to='group_app.groupmember', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Направление экспертизы',
                'verbose_name_plural': 'Направления экспертизы',
                'ordering': ['position', 'id'],
            },
        ),
    ]
