# Generated by Django 5.2.5 on 2026-03-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0005_orgunit_short_name'),
        ('policy_app', '0019_add_expertise_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertisedirection',
            name='owner',
        ),
        migrations.AddField(
            model_name='expertisedirection',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='expertise_directions', to='group_app.groupmember', verbose_name='Владельцы'),
        ),
    ]
