# Generated by Django 5.2.5 on 2026-03-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0005_orgunit_short_name'),
        ('policy_app', '0020_expertise_direction_m2m_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_group_owner',
            field=models.BooleanField(default=False, verbose_name='Группа (все компании)'),
        ),
        migrations.AddField(
            model_name='product',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='products', to='group_app.groupmember', verbose_name='Владельцы'),
        ),
    ]
