# Generated by Django 5.2.5 on 2026-03-17 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers_app', '0013_legalentityrecord'),
        ('policy_app', '0021_product_m2m_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='recommended_specialist',
        ),
        migrations.AddField(
            model_name='grade',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='classifiers_app.okvcurrency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='grade',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Часовая ставка'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='service_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Объем услуг в часах'),
        ),
    ]
