# Generated by Django 5.2.5 on 2026-03-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0022_remove_tariff_recommended_specialist_grade_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertisedirection',
            name='pricing_method',
            field=models.CharField(blank=True, choices=[('vpm', 'Ставка в ВПМ'), ('hours', 'Объем услуг в часах')], default='', max_length=16, verbose_name='Расчет стоимости услуг'),
        ),
    ]
