# Generated by Django 5.2.5 on 2026-03-18 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0023_expertisedirection_pricing_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='typicalsection',
            name='expertise_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typical_sections_dir', to='policy_app.expertisedirection', verbose_name='Экспертиза'),
        ),
    ]
