# Generated by Django 5.2.5 on 2026-04-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy_app", "0037_typicalservicecomposition_editor_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="consulting_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Горный", "Горный"),
                    ("Геологический", "Геологический"),
                    ("Экологический", "Экологический"),
                    ("Спецуслуги", "Спецуслуги"),
                ],
                default="",
                max_length=64,
                verbose_name="Вид консалтинга",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="service_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Аудит", "Аудит"),
                    ("Инжиниринг", "Инжиниринг"),
                    ("Оценка", "Оценка"),
                    ("Сопровождение", "Сопровождение"),
                    ("Исследование", "Исследование"),
                    ("Спецуслуги", "Спецуслуги"),
                ],
                default="",
                max_length=64,
                verbose_name="Тип услуг",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="service_code",
            field=models.CharField(blank=True, default="", max_length=1, verbose_name="Код"),
        ),
        migrations.RenameField(
            model_name="product",
            old_name="service_type",
            new_name="service_subtype",
        ),
        migrations.AlterField(
            model_name="product",
            name="service_subtype",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Подтип услуги"),
        ),
    ]
