# Generated by Django 5.2.5 on 2026-06-25 13:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0048_typicalserviceterm_term_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Уровень')),
                ('code', models.CharField(blank=True, default='', max_length=255, verbose_name='Код')),
                ('name', models.TextField(blank=True, default='', verbose_name='Наименование отчета, раздела (подраздела)')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_structures', to='policy_app.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Типовая структура отчета',
                'verbose_name_plural': 'Типовая структура отчета',
                'ordering': ['product_id', 'position', 'id'],
            },
        ),
    ]
