# Generated by Django 5.2.5 on 2026-02-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OKSMCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='№')),
                ('code', models.CharField(max_length=3, verbose_name='Код')),
                ('short_name', models.CharField(max_length=255, verbose_name='Наименование страны (краткое)')),
                ('full_name', models.CharField(blank=True, default='', max_length=512, verbose_name='Наименование страны (полное)')),
                ('alpha2', models.CharField(max_length=2, verbose_name='Буквенный код (Альфа-2)')),
                ('alpha3', models.CharField(max_length=3, verbose_name='Буквенный код (Альфа-3)')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Страна (ОКСМ)',
                'verbose_name_plural': 'Страны (ОКСМ)',
                'ordering': ['position', 'id'],
            },
        ),
    ]
