# Generated by Django 5.2.5 on 2026-02-27 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritorialDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255, verbose_name='Регион')),
                ('region_code', models.CharField(max_length=32, verbose_name='Код региона')),
                ('effective_date', models.DateField(verbose_name='Дата')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territorial_divisions', to='classifiers_app.oksmcountry', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Административно-территориальная единица',
                'verbose_name_plural': 'Административно-территориальное деление',
                'ordering': ['country__short_name', '-effective_date', 'position', 'id'],
            },
        ),
    ]
