# Generated by Django 5.2.5 on 2026-02-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers_app', '0002_territorialdivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorialdivision',
            name='abolished_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата упразднения'),
        ),
        migrations.AlterField(
            model_name='territorialdivision',
            name='effective_date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
    ]
