# Generated by Django 5.2.5 on 2026-02-27 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers_app', '0003_territorialdivision_abolished_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivingWage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Величина прожиточного минимума')),
                ('currency', models.CharField(max_length=50, verbose_name='Валюта')),
                ('approval_date', models.DateField(verbose_name='Дата утверждения')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата прекращения действия')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='living_wages', to='classifiers_app.oksmcountry', verbose_name='Страна')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='living_wages', to='classifiers_app.territorialdivision', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Величина прожиточного минимума',
                'verbose_name_plural': 'Величины прожиточного минимума',
                'ordering': ['country__short_name', 'region__region_name', 'position', 'id'],
            },
        ),
    ]
