# Generated by Django 5.2.5 on 2026-02-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers_app', '0004_livingwage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livingwage',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Величина прожиточного минимума', 'verbose_name_plural': 'Величины прожиточного минимума'},
        ),
        migrations.AlterModelOptions(
            name='territorialdivision',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Административно-территориальная единица', 'verbose_name_plural': 'Административно-территориальное деление'},
        ),
    ]
