# Generated by Django 5.2.5 on 2026-02-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers_app', '0005_alter_livingwage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OKVCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_numeric', models.CharField(max_length=3, verbose_name='Код 000')),
                ('code_alpha', models.CharField(max_length=3, verbose_name='Код AAA')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование валюты')),
                ('abbreviation', models.CharField(blank=True, default='', max_length=50, verbose_name='Сокращенное обозначение')),
                ('symbol', models.CharField(blank=True, default='', max_length=10, verbose_name='Символ')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countries', models.ManyToManyField(blank=True, related_name='currencies', to='classifiers_app.oksmcountry', verbose_name='Страны использования')),
            ],
            options={
                'verbose_name': 'Валюта (ОКВ)',
                'verbose_name_plural': 'Валюты (ОКВ)',
                'ordering': ['position', 'id'],
            },
        ),
    ]
