# Generated by Django 5.2.5 on 2026-02-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers_app', '0006_okvcurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='oksmcountry',
            name='approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата утверждения'),
        ),
        migrations.AddField(
            model_name='oksmcountry',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прекращения действия'),
        ),
        migrations.AddField(
            model_name='oksmcountry',
            name='source',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Источник'),
        ),
    ]
