# Generated by Django 5.2.5 on 2026-02-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers_app', '0007_oksmcountry_approval_date_oksmcountry_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='okvcurrency',
            name='countries_codes',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Коды стран использования'),
        ),
    ]
