# Generated by Django 5.2.5 on 2026-02-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers_app', '0008_okvcurrency_countries_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='okvcurrency',
            name='approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата утверждения'),
        ),
        migrations.AddField(
            model_name='okvcurrency',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прекращения действия'),
        ),
        migrations.AddField(
            model_name='okvcurrency',
            name='source',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Источник'),
        ),
    ]
