# Generated by Django 5.2.5 on 2026-02-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers_app', '0009_okvcurrency_approval_date_okvcurrency_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livingwage',
            name='source',
            field=models.TextField(blank=True, default='', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='territorialdivision',
            name='source',
            field=models.TextField(blank=True, default='', verbose_name='Источник'),
        ),
    ]
