# Generated by Django 5.2.5 on 2026-03-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers_app', '0010_livingwage_source_territorialdivision_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntityIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64, verbose_name='Идентификатор')),
                ('full_name', models.CharField(max_length=512, verbose_name='Наименование идентификатора (полное)')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_entity_identifiers', to='classifiers_app.oksmcountry', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Идентификатор юрлица',
                'verbose_name_plural': 'Классификатор идентификаторов юрлиц',
                'ordering': ['position', 'id'],
            },
        ),
    ]
