# Generated by Django 5.2.5 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers_app', '0011_legalentityidentifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentityidentifier',
            name='code',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Код'),
        ),
    ]
