# Generated by Django 5.2.5 on 2025-09-14 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Позиция"
                    ),
                ),
                ("number", models.CharField(max_length=50, verbose_name="Номер")),
                (
                    "type",
                    models.CharField(blank=True, max_length=100, verbose_name="Тип"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "status",
                    models.CharField(blank=True, max_length=100, verbose_name="Статус"),
                ),
                (
                    "contract_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Начало контракта"
                    ),
                ),
                (
                    "contract_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Окончание контракта"
                    ),
                ),
                (
                    "completion_calc",
                    models.DateField(
                        blank=True, null=True, verbose_name="Окончание, расчет"
                    ),
                ),
                (
                    "input_data",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Исх. данные"
                    ),
                ),
                (
                    "stage1_weeks",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Этап 1, недель"
                    ),
                ),
                (
                    "stage1_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Этап 1, дата окончания"
                    ),
                ),
                (
                    "stage2_weeks",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Этап 2, недель"
                    ),
                ),
                (
                    "stage2_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Этап 2, дата окончания"
                    ),
                ),
                (
                    "stage3_weeks",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Этап 3, недель"
                    ),
                ),
                (
                    "term_weeks",
                    models.PositiveIntegerField(default=0, verbose_name="Срок, недель"),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Дедлайн"),
                ),
                (
                    "year",
                    models.IntegerField(blank=True, null=True, verbose_name="Год"),
                ),
                (
                    "customer",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заказчик"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Регистрационный номер"
                    ),
                ),
                (
                    "project_manager",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Руководитель проекта"
                    ),
                ),
                (
                    "deadline_format",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Дедлайн, формат"
                    ),
                ),
                (
                    "contract_subject",
                    models.TextField(blank=True, verbose_name="Предмет договора"),
                ),
            ],
            options={
                "verbose_name": "Регистрация проекта",
                "verbose_name_plural": "Регистрация проекта",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Позиция"
                    ),
                ),
                (
                    "type",
                    models.CharField(blank=True, max_length=100, verbose_name="Тип"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "asset_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Наименование актива"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Регистрационный номер"
                    ),
                ),
                (
                    "manager",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Менеджер"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_items",
                        to="projects_app.projectregistration",
                        verbose_name="Номер проекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объем работ",
                "verbose_name_plural": "Объем работ",
                "ordering": ["project__position", "position", "id"],
            },
        ),
    ]
