# Generated by Django 5.2.5 on 2025-09-21 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0002_update_projectregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectregistration",
            name="number",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(3333),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="Номер",
            ),
        ),
    ]
