# Generated by Django 5.2.5 on 2025-09-21 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy_app", "0005_alter_typicalsection_options"),
        ("projects_app", "0003_alter_projectregistration_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Performer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(db_index=True, default=1)),
                (
                    "asset_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Актив"
                    ),
                ),
                (
                    "executor",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Грейд"
                    ),
                ),
                (
                    "actual_costs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Фактические затраты",
                    ),
                ),
                (
                    "estimated_costs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Расчетные затраты",
                    ),
                ),
                (
                    "agreed_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Согласованная сумма",
                    ),
                ),
                (
                    "prepayment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Аванс",
                    ),
                ),
                (
                    "final_payment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Окон. платеж",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Номер договора",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performers",
                        to="projects_app.projectregistration",
                        verbose_name="Регистрация проекта",
                    ),
                ),
                (
                    "typical_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performer_items",
                        to="policy_app.typicalsection",
                        verbose_name="Типовой раздел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Исполнитель",
                "verbose_name_plural": "Исполнители",
                "ordering": ["position", "id"],
            },
        ),
    ]
