# Generated by Django 5.2.5 on 2025-11-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0005_registration_agreement_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectregistration",
            name="agreement_type",
            field=models.CharField(
                choices=[("MAIN", "Основной договор"), ("ADDENDUM", "Допсоглашение")],
                db_index=True,
                default="MAIN",
                max_length=20,
                verbose_name="Вид соглашения",
            ),
        ),
    ]
