# Generated by Django 5.2.5 on 2025-11-15 11:32
from django.db import migrations, models


def populate_short_uid(apps, schema_editor):
    ProjectRegistration = apps.get_model("projects_app", "ProjectRegistration")
    seen = {}
    # стабильный порядок, чтобы индексы воспроизводились
    for pr in ProjectRegistration.objects.order_by("number", "group", "position", "id"):
        key = (pr.number, pr.group)
        idx = seen.get(key, 0)
        pr.short_uid = f"{pr.number}{pr.group}-{idx}"
        pr.save(update_fields=["short_uid"])
        seen[key] = idx + 1


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0006_alter_projectregistration_agreement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectregistration",
            name="short_uid",
            field=models.CharField(
                verbose_name="Проект ID",
                max_length=32,
                editable=False,
                blank=True,
                null=True,
            ),
        ),
        migrations.RunPython(populate_short_uid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="projectregistration",
            name="short_uid",
            field=models.CharField(
                verbose_name="Проект ID",
                max_length=32,
                editable=False,
                unique=True,
                db_index=True,
            ),
        ),
    ]