# Generated by Django 5.2.5 on 2025-11-23 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0013_legalentity_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectregistration",
            name="short_uid",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=32,
                unique=True,
                verbose_name="Проект ID",
            ),
        ),
        migrations.AlterField(
            model_name="projectregistration",
            name="stage3_weeks",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
