# Generated by Django 5.2.5 on 2026-03-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0018_performer_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='info_approval_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа на запрос согласования'),
        ),
        migrations.AddField(
            model_name='performer',
            name='info_approval_status',
            field=models.CharField(blank=True, choices=[('not_approved', 'Не согласован'), ('approved', 'Согласован')], default='', max_length=20, verbose_name='Статус согласования'),
        ),
        migrations.AddField(
            model_name='performer',
            name='info_request_deadline_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок согласования'),
        ),
        migrations.AddField(
            model_name='performer',
            name='info_request_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки запроса согласования'),
        ),
    ]
