# Generated by Django 5.2.5 on 2026-03-12 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers_app', '0012_legalentityidentifier_code'),
        ('projects_app', '0019_performer_info_approval_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectregistration',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_registrations', to='classifiers_app.oksmcountry', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='projectregistration',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Идентификатор'),
        ),
    ]
