# Generated by Django 5.2.5 on 2026-03-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0020_add_country_and_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectregistration",
            name="registration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата регистрации"
            ),
        ),
    ]
