# Generated by Django 5.2.5 on 2026-03-13 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifiers_app", "0012_legalentityidentifier_code"),
        ("projects_app", "0022_add_work_volume_country_identifier_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalentity",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legal_entities",
                to="classifiers_app.oksmcountry",
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="identifier",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Идентификатор"
            ),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="registration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата регистрации"
            ),
        ),
    ]
