# Generated by Django 5.2.5 on 2026-03-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0023_add_legal_entity_country_identifier_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='performer',
            name='grade_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Грейд (наименование)'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Грейд (уровень)'),
        ),
    ]
