# Generated by Django 5.2.5 on 2026-03-13 15:43

import django.db.models.deletion
from django.db import migrations, models


def clear_empty_currency(apps, schema_editor):
    Performer = apps.get_model('projects_app', 'Performer')
    Performer.objects.filter(currency='').update(currency=None)


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers_app', '0012_legalentityidentifier_code'),
        ('projects_app', '0024_add_grade_name_and_currency'),
    ]

    operations = [
        # First make the CharField nullable so empty strings can become NULL
        migrations.AlterField(
            model_name='performer',
            name='currency',
            field=models.CharField(blank=True, null=True, default='', max_length=50, verbose_name='Валюта'),
        ),
        # Convert empty strings to NULL via Python
        migrations.RunPython(clear_empty_currency, migrations.RunPython.noop),
        # Now convert to ForeignKey
        migrations.AlterField(
            model_name='performer',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performers', to='classifiers_app.okvcurrency', verbose_name='Валюта'),
        ),
    ]
