# Generated by Django 5.2.5 on 2026-03-13 15:43

import django.db.models.deletion
from django.db import migrations, models


def clear_empty_currency(apps, schema_editor):
    schema_editor.execute(
        "ALTER TABLE projects_app_performer ALTER COLUMN currency DROP NOT NULL"
    )
    schema_editor.execute(
        "UPDATE projects_app_performer SET currency = NULL WHERE currency = ''"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers_app', '0012_legalentityidentifier_code'),
        ('projects_app', '0024_add_grade_name_and_currency'),
    ]

    operations = [
        migrations.RunPython(clear_empty_currency, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='performer',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performers', to='classifiers_app.okvcurrency', verbose_name='Валюта'),
        ),
    ]
