# Generated by Django 5.2.5 on 2026-03-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0025_change_currency_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='contract_conclusion_status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Статус заключения договора'),
        ),
        migrations.AddField(
            model_name='performer',
            name='contract_deadline_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок подписания договора'),
        ),
        migrations.AddField(
            model_name='performer',
            name='contract_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки проекта договора'),
        ),
        migrations.AddField(
            model_name='performer',
            name='contract_signing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подписания'),
        ),
        migrations.AddField(
            model_name='performer',
            name='contract_signing_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подписание'),
        ),
    ]
