# Generated by Django 5.2.5 on 2026-03-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0026_add_contract_conclusion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='contract_file',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Файл договора'),
        ),
        migrations.AddField(
            model_name='performer',
            name='contract_term',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Срок договора'),
        ),
    ]
