# Generated by Django 5.2.5 on 2026-03-16 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0033_add_user_to_workspace_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDataTargetFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_data_target_folder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Целевая папка исходных данных',
                'verbose_name_plural': 'Целевые папки исходных данных',
            },
        ),
    ]
