# Generated by Django 5.2.5 on 2026-03-18 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0034_sourcedatatargetfolder'),
        ('users_app', '0004_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformerParticipationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor_name', models.CharField(max_length=255, verbose_name='Исполнитель (ФИО)')),
                ('request_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки запроса')),
                ('deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок подтверждения')),
                ('response', models.CharField(blank=True, choices=[('confirmed', 'Подтверждаю участие'), ('declined', 'Не готов(а) участвовать')], default='', max_length=20, verbose_name='Ответ на запрос')),
                ('response_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participation_snapshots', to='users_app.employee', verbose_name='Сотрудник')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_snapshots', to='projects_app.performer', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Снимок подтверждения участия',
                'verbose_name_plural': 'Снимки подтверждений участия',
                'ordering': ['request_sent_at', 'id'],
            },
        ),
    ]
