# Generated by Django 5.2.5 on 2026-03-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0040_performer_contract_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='contract_employee_scan',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Скан с подписью сотрудника'),
        ),
        migrations.AddField(
            model_name='performer',
            name='contract_send_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AddField(
            model_name='performer',
            name='contract_signed_scan',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Скан подписанного договора'),
        ),
        migrations.AddField(
            model_name='performer',
            name='contract_upload_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загрузки'),
        ),
    ]
