# Generated by Django 5.2.5 on 2026-03-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0044_performer_contract_employee_scan_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='contract_signed_scan_file',
            field=models.FileField(blank=True, default='', upload_to='contract_signed_scans/', verbose_name='Файл подписанного договора'),
        ),
        migrations.AddField(
            model_name='performer',
            name='contract_signed_scan_link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Ссылка на подписанный договор'),
        ),
        migrations.AddField(
            model_name='performer',
            name='contract_signed_scan_upload_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата загрузки подписанного договора'),
        ),
    ]
