# Generated by Django 5.2.5 on 2026-03-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0045_performer_contract_signed_scan_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='contract_send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
    ]
