# Generated by Django 5.2.5 on 2026-05-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0077_projectregistration_proposal_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequestPerformer',
            fields=[
            ],
            options={
                'verbose_name': 'Заявка на оплату',
                'verbose_name_plural': 'Заявки на оплату',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects_app.performer',),
        ),
    ]
