# Generated by Django 5.2.5 on 2026-03-15 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('participation_confirmation', 'Подтверждение участия'), ('contract_sending', 'Отправка проекта договора'), ('project_start', 'Начало проекта'), ('request_approval', 'Согласование запроса')], db_index=True, max_length=64, verbose_name='Тип шаблона')),
                ('body_html', models.TextField(verbose_name='Тело письма (HTML)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Шаблон по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_templates', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('template_type', 'user'), name='unique_letter_template_per_user_type')],
            },
        ),
    ]
