# Generated by Django 5.2.5 on 2026-03-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters_app', '0002_default_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettertemplate',
            name='subject_template',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Заголовок письма (шаблон)'),
        ),
    ]
