# Generated by Django 5.2.5 on 2026-03-15 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters_app', '0004_populate_default_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lettertemplate',
            name='cc_recipients',
            field=models.ManyToManyField(blank=True, related_name='letter_cc_templates', to=settings.AUTH_USER_MODEL, verbose_name='Копия'),
        ),
    ]
