# Generated by Django 5.2.5 on 2026-03-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters_app", "0007_add_direction_confirmation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lettertemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("participation_confirmation", "Подтверждение участия эксперта"),
                    ("direction_confirmation", "Подтверждение по направлению"),
                    ("contract_sending", "Отправка проекта договора"),
                    ("project_start", "Начало проекта"),
                    ("request_approval", "Согласование запроса"),
                ],
                db_index=True,
                max_length=64,
                verbose_name="Тип шаблона",
            ),
        ),
    ]
