from django.urls import path

from . import views


urlpatterns = [
    path("prs/autocomplete/", views.prs_autocomplete, name="prs_autocomplete"),
    path("prs/filter-options/", views.prs_filter_options, name="prs_filter_options"),
    path("prs/birth-date/", views.prs_birth_date, name="prs_birth_date"),
    path("adr/registration-autofill/", views.adr_registration_autofill, name="adr_registration_autofill"),
    path("prs/table/", views.prs_table_partial, name="prs_table_partial"),
    path("prs/create/", views.prs_form_create, name="prs_form_create"),
    path("prs/<int:pk>/edit/", views.prs_form_edit, name="prs_form_edit"),
    path("prs/<int:pk>/delete/", views.prs_delete, name="prs_delete"),
    path("prs/<int:pk>/move-up/", views.prs_move_up, name="prs_move_up"),
    path("prs/<int:pk>/move-down/", views.prs_move_down, name="prs_move_down"),
    path("ctz/table/", views.ctz_table_partial, name="ctz_table_partial"),
    path("ctz/identifier-for-country/", views.ctz_identifier_for_country, name="ctz_identifier_for_country"),
    path("ctz/create/", views.ctz_form_create, name="ctz_form_create"),
    path("ctz/<int:pk>/edit/", views.ctz_form_edit, name="ctz_form_edit"),
    path("ctz/<int:pk>/delete/", views.ctz_delete, name="ctz_delete"),
    path("ctz/<int:pk>/move-up/", views.ctz_move_up, name="ctz_move_up"),
    path("ctz/<int:pk>/move-down/", views.ctz_move_down, name="ctz_move_down"),
    path("adr/table/", views.adr_table_partial, name="adr_table_partial"),
    path("adr/create/", views.adr_form_create, name="adr_form_create"),
    path("adr/<int:pk>/edit/", views.adr_form_edit, name="adr_form_edit"),
    path("adr/<int:pk>/delete/", views.adr_delete, name="adr_delete"),
    path("adr/<int:pk>/move-up/", views.adr_move_up, name="adr_move_up"),
    path("adr/<int:pk>/move-down/", views.adr_move_down, name="adr_move_down"),
    path("psn/table/", views.psn_table_partial, name="psn_table_partial"),
    path("psn/create/", views.psn_form_create, name="psn_form_create"),
    path("psn/<int:pk>/edit/", views.psn_form_edit, name="psn_form_edit"),
    path("psn/<int:pk>/delete/", views.psn_delete, name="psn_delete"),
    path("psn/<int:pk>/move-up/", views.psn_move_up, name="psn_move_up"),
    path("psn/<int:pk>/move-down/", views.psn_move_down, name="psn_move_down"),
    path("tel/table/", views.tel_table_partial, name="tel_table_partial"),
    path("tel/ru-landline-lookup/", views.tel_ru_landline_lookup, name="tel_ru_landline_lookup"),
    path("tel/create/", views.tel_form_create, name="tel_form_create"),
    path("tel/<int:pk>/edit/", views.tel_form_edit, name="tel_form_edit"),
    path("tel/<int:pk>/delete/", views.tel_delete, name="tel_delete"),
    path("tel/<int:pk>/move-up/", views.tel_move_up, name="tel_move_up"),
    path("tel/<int:pk>/move-down/", views.tel_move_down, name="tel_move_down"),
    path("eml/table/", views.eml_table_partial, name="eml_table_partial"),
    path("eml/create/", views.eml_form_create, name="eml_form_create"),
    path("eml/<int:pk>/edit/", views.eml_form_edit, name="eml_form_edit"),
    path("eml/<int:pk>/delete/", views.eml_delete, name="eml_delete"),
    path("eml/<int:pk>/move-up/", views.eml_move_up, name="eml_move_up"),
    path("eml/<int:pk>/move-down/", views.eml_move_down, name="eml_move_down"),
]
