# Generated by Django 5.2.5 on 2026-03-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_choice',
            field=models.CharField(blank=True, choices=[('', 'Не выбрано'), ('confirmed', 'Подтвердить участие'), ('declined', 'Отклонить'), ('approved', 'Согласовать запрос')], default='', max_length=20, verbose_name='Действие по уведомлению'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_participation_confirmation', 'Запрос подтверждения участия в проекте'), ('project_info_request_approval', 'Согласование запроса информации')], db_index=True, max_length=64, verbose_name='Тип уведомления'),
        ),
    ]
