# Generated by Django 5.2.5 on 2026-03-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0002_alter_notification_action_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_section',
            field=models.CharField(choices=[('none', 'Не указан'), ('projects', 'Проекты'), ('checklists', 'Чек-листы')], db_index=True, default='none', max_length=32, verbose_name='Раздел'),
        ),
    ]
