# Generated by Django 5.2.5 on 2026-03-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0003_alter_notification_related_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_participation_confirmation', 'Запрос подтверждения участия в проекте'), ('project_info_request_approval', 'Согласование запроса информации'), ('project_contract_conclusion', 'Отправлен проект договора')], db_index=True, max_length=64, verbose_name='Тип уведомления'),
        ),
    ]
