from django.urls import path
from . import views

urlpatterns = [
    path("projects/partial/", views.projects_partial, name="projects_partial"),

    path("projects/registration/create/", views.registration_form_create, name="registration_form_create"),
    path("projects/registration/<int:pk>/edit/", views.registration_form_edit, name="registration_form_edit"),
    path("projects/registration/<int:pk>/delete/", views.registration_delete, name="registration_delete"),
    path("projects/registration/<int:pk>/launch/", views.registration_launch, name="registration_launch"),
    path("projects/registration/<int:pk>/status/", views.registration_status_update, name="registration_status_update"),
    path("projects/registration/<int:pk>/manager/", views.registration_manager_update, name="registration_manager_update"),
    path("projects/registration/<int:pk>/deadline/", views.registration_deadline_update, name="registration_deadline_update"),
    path("projects/registration/<int:pk>/evaluation-date/", views.registration_evaluation_date_update, name="registration_evaluation_date_update"),
    path("projects/registration/<int:pk>/move-up/", views.registration_move_up, name="registration_move_up"),
    path("projects/registration/<int:pk>/move-down/", views.registration_move_down, name="registration_move_down"),
    path("projects/registration/<int:pk>/gantt/", views.project_schedule_gantt, name="project_schedule_gantt"),
    path("projects/registration/create-workspace/", views.create_registration_workspace, name="create_registration_workspace"),
    path("projects/registration/workspace-folders/", views.workspace_folders_list, name="workspace_folders_list"),
    path("projects/registration/workspace-folders/save/", views.workspace_folders_save, name="workspace_folders_save"),
    path("projects/registration/workspace-folders/reset/", views.workspace_folders_reset, name="workspace_folders_reset"),
    path("projects/reports/upload/", views.report_file_upload, name="report_file_upload"),
    path("projects/reports/send/", views.report_file_send, name="report_file_send"),
    path("projects/reports/<int:pk>/download/", views.report_file_download, name="report_file_download"),
    path("projects/reports/<int:pk>/check-download/", views.report_check_file_download, name="report_check_file_download"),
    path("projects/report-checks/create/", views.report_check_form_create, name="report_check_form_create"),
    path("projects/report-checks/<int:pk>/edit/", views.report_check_form_edit, name="report_check_form_edit"),
    path("projects/report-checks/<int:pk>/delete/", views.report_check_delete, name="report_check_delete"),
    path("projects/report-checks/<int:pk>/move-up/", views.report_check_move_up, name="report_check_move_up"),
    path("projects/report-checks/<int:pk>/move-down/", views.report_check_move_down, name="report_check_move_down"),
    path("projects/report-macros/create/", views.report_macro_form_create, name="report_macro_form_create"),
    path("projects/report-macros/<int:pk>/edit/", views.report_macro_form_edit, name="report_macro_form_edit"),
    path("projects/report-macros/<int:pk>/delete/", views.report_macro_delete, name="report_macro_delete"),
    path("projects/report-macros/<int:pk>/move-up/", views.report_macro_move_up, name="report_macro_move_up"),
    path("projects/report-macros/<int:pk>/move-down/", views.report_macro_move_down, name="report_macro_move_down"),

    path("projects/contract/<int:pk>/edit/", views.contract_form_edit, name="contract_form_edit"),

    path("projects/registration/<int:pk>/gantt/task/add/", views.project_schedule_form_create, name="project_schedule_form_create"),
    path("projects/registration/<int:project_pk>/gantt/task/<str:task_id>/edit/", views.project_schedule_form_edit, name="project_schedule_form_edit"),
    path("projects/registration/<int:project_pk>/gantt/task/<str:task_id>/delete/", views.project_schedule_delete, name="project_schedule_delete"),
    path("projects/registration/<int:project_pk>/gantt/task/<str:task_id>/move-up/", views.project_schedule_move_up, name="project_schedule_move_up"),
    path("projects/registration/<int:project_pk>/gantt/task/<str:task_id>/move-down/", views.project_schedule_move_down, name="project_schedule_move_down"),

    path("projects/work/create/", views.work_form_create, name="work_form_create"),
    path("projects/work/<int:pk>/edit/",  views.work_form_edit, name="work_form_edit"),
    path("projects/work/<int:pk>/delete/", views.work_delete, name="work_delete"),
    path("projects/work/<int:pk>/move-up/", views.work_move_up, name="work_move_up"),
    path("projects/work/<int:pk>/move-down/", views.work_move_down, name="work_move_down"),

    path("projects/performers/partial/", views.performers_partial, name="performers_partial"),
    path("projects/performers/create/", views.performer_form_create, name="performer_form_create"),
    path("projects/performers/<int:pk>/edit/", views.performer_form_edit, name="performer_form_edit"),
    path("projects/performers/<int:pk>/delete/", views.performer_delete, name="performer_delete"),
    path("projects/performers/<int:pk>/move-up/", views.performer_move_up, name="performer_move_up"),
    path("projects/performers/<int:pk>/move-down/", views.performer_move_down, name="performer_move_down"),
    path("projects/performers/row-order/", views.performer_row_order, name="performer_row_order"),
    path("projects/performers/participation-batch/merge/", views.participation_batch_merge, name="participation_batch_merge"),
    path("projects/performers/participation-batch/split/", views.participation_batch_split, name="participation_batch_split"),
    path("projects/performers/request-confirmation/", views.participation_request, name="participation_request"),
    path("projects/performers/send-contract/", views.contract_request, name="contract_request"),
    path("projects/performers/request-info-approval/", views.info_request_approval, name="info_request_approval"),
    path("projects/performers/revoke-info-approval/", views.revoke_info_request_approval, name="revoke_info_request_approval"),
    path("projects/performers/payment-request/", views.payment_request, name="payment_request"),
    path(
        "projects/performers/payment-paid-toggle/",
        views.payment_paid_toggle,
        name="payment_paid_toggle",
    ),
    path("projects/performers/create-workspace/", views.create_workspace, name="create_workspace"),
    path("projects/performers/create-source-data-workspace/", views.create_source_data_workspace, name="create_source_data_workspace"),
    path("projects/performers/source-data-target-folder/", views.source_data_target_folder_load, name="source_data_target_folder_load"),
    path("projects/performers/source-data-target-folder/save/", views.source_data_target_folder_save, name="source_data_target_folder_save"),
    path("projects/performers/contract-project-target-folder/", views.contract_project_target_folder_load, name="contract_project_target_folder_load"),
    path("projects/performers/contract-project-target-folder/save/", views.contract_project_target_folder_save, name="contract_project_target_folder_save"),
    path("projects/performers/contract-docx-source/<int:pk>/", views.contract_onlyoffice_docx_source, name="contract_onlyoffice_docx_source"),
    path("projects/performers/sign-contract/", views.sign_contract_documents, name="sign_contract_documents"),
    path("projects/performers/sign-performer-contract/", views.sign_performer_contract_documents, name="sign_performer_contract_documents"),
    path("projects/performers/create-contract-project/", views.create_contract_project, name="create_contract_project"),

    path("projects/legal-entities/create/", views.legal_entity_form_create, name="legal_entity_form_create"),
    path("projects/legal-entities/<int:pk>/edit/", views.legal_entity_form_edit, name="legal_entity_form_edit"),
    path("projects/legal-entities/<int:pk>/delete/", views.legal_entity_delete, name="legal_entity_delete"),
    path("projects/legal-entities/<int:pk>/move-up/", views.legal_entity_move_up, name="legal_entity_move_up"),
    path("projects/legal-entities/<int:pk>/move-down/", views.legal_entity_move_down, name="legal_entity_move_down"),
    path("projects/legal-entities/work-deps/", views.legal_entity_work_deps, name="legal_entity_work_deps"),

    path("projects/work/deps/", views.work_deps, name="work_deps"),
    path("projects/identifier-for-country/", views.identifier_for_country, name="identifier_for_country"),
]
