name: CI + Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - env:
          DJANGO_SETTINGS_MODULE: settings
          SECRET_KEY: dummy
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_ai_app
        run: |
          python manage.py check
          pytest -q

  deploy:
    needs: test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}      # 130.193.53.106
          username: ${{ secrets.SSH_USER }}  # sergei
          key: ${{ secrets.SSH_KEY }}        # приватный ключ
          script: |
            set -e
            cd ~/ai_appdir/ai_app
            git fetch origin
            git switch main
            git pull --ff-only
            source ~/ai_appdir/ai_appenv/bin/activate
            pip install -r requirements.txt
            export DJANGO_SETTINGS_MODULE=settings
            python -m django migrate --noinput
            python -m django collectstatic --noinput
            sudo systemctl restart gunicorn
            echo "Deploy OK"
